[package]
name = "launchpad-emulator-app"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[[bin]]
name = "launchpad-emulator"
path = "src/main.rs"

[dependencies]
eframe = "0.36"
launchpad-emulator = { version = "0.1.0", path = "../launchpad-emulator" }
launchpad-emulator-ui = { version = "0.1.0", path = "../launchpad-emulator-ui" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
